import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const About: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>yeahhhhhhhhhhhhhhhhhh</h1>

        <div>
          <Link href='/'>
            <a>Indexページへ移動</a>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default About
